# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define "entice-imagesynth", primary: true do |server|
    server.vm.box = "bento/ubuntu-14.04"
    server.vm.synced_folder "..", "/vagrant", disabled: false
    #server.vm.network "forwarded_port", guest: 22, host: 2222
    server.vm.provider "virtualbox" do |vb|
      #vb.gui = true
      vb.cpus = 2
      vb.memory = 1536
      vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
    end
    server.vm.provision "shell", inline: $script
  end
end
