source "https://supermarket.chef.io"

metadata

cookbook 'wordpress', '~> 3.0.0'
cookbook 'selinux', '~> 0.7'
cookbook 'php-fpm', '~> 0.6.10'
cookbook 'nginx', '~> 2.7.4'
cookbook 'tar', '>= 0.3.1'
cookbook 'build-essential', '>= 0.0.0'
cookbook 'mysql2_chef_gem', '~> 1.0.1'
cookbook 'mysql', '>= 6.0'
cookbook 'database', '>= 1.6.0'
cookbook 'apache2', '>= 2.0.0'
cookbook 'openssl', '>= 0.0.0'
cookbook 'php', '>= 0.0.0'
